/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bp_projetbanque_GestionCheque_MonDriver */

#ifndef _Included_bp_projetbanque_GestionCheque_MonDriver
#define _Included_bp_projetbanque_GestionCheque_MonDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bp_projetbanque_GestionCheque_MonDriver
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bp_projetbanque_GestionCheque_MonDriver_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
